---
- name: Stop and disable firewalld  | RedHat
  service:
    name: firewalld
    state: stopped
    enabled: False
  ignore_errors: True
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  become: yes
  tags: iptables

- name: Install iptables | RedHat
  package:
    name: iptables-services
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  become: yes
  tags: iptables
 
- name: Install iptables | Debian
  package:
    name: iptables-persistent
    state: present
  when: ansible_os_family == "Debian"
  become: yes
  tags: iptables
  
- name: Set custom iptables rules
  iptables_raw:
    name: 'iptables_custom_rules_{{ item.name }}'
    rules: '{{ item.rules }}'
    state: '{{ item.state }}'
    weight: '{{ item.weight|default(omit) }}'
    table: '{{ item.table|default(omit) }}'
  with_items: '{{ iptables_custom_rules }}'
  become: yes
  tags: iptables

- name: Set default iptables head rules
  iptables_raw:
    name: iptables_default_head
    weight: 10
    keep_unmanaged: '{{ iptables_keep_unmanaged }}'
    state: present
    rules: '{{ iptables_default_head }}'
  become: yes
  tags: iptables

- name: Set default iptables tail rules
  iptables_raw:
    name: iptables_default_tail
    weight: 99
    keep_unmanaged: '{{ iptables_keep_unmanaged }}'
    state: '{{ (iptables_default_tail != "" ) | ternary("present", "absent") }}'
    rules: '{{ iptables_default_tail }}'
  become: yes
  tags: iptables
  
- name: Enable and start iptables service | RedHat
  service:
    name: iptables
    state: started
    enabled: True
  when: ansible_os_family == "RedHat"
  become: yes
  tags: iptables

- name: Enable and start iptables service | Ubuntu before 16.04
  service:
    name: iptables-persistent
    state: started
    enabled: True
  changed_when: False     # The service 'iptables-persistent' doesn't have 'status' state. So, it always reports changed state to Ansible.
  when: ansible_os_family == "Debian" and ansible_lsb.major_release|int < 16
  become: yes
  tags: iptables

- name: Enable and start iptables service | Ubuntu 16.04
  service:
    name: netfilter-persistent
    state: started
    enabled: True
  changed_when: False     # The service 'iptables-persistent' doesn't have 'status' state. So, it always reports changed state to Ansible.
  when: ansible_os_family == "Debian" and ansible_lsb.major_release|int >= 16
  become: yes
  tags: iptables
